{% set name = "roslibpy" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7e3c42a2c6a5f35d9deda9979ff11e8ffec3388f40329e22b56ad2122228cb55

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - roslibpy=roslibpy.__main__:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - autobahn >=17.10
    - twisted >=17.9
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - roslibpy

about:
  home: https://github.com/gramaziokohler/roslibpy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python ROS Bridge library
  description: |
    Python ROS Bridge library allows to use Python and IronPython to interact
    with ROS, the open-source robotic middleware. It uses WebSockets to
    connect to rosbridge 2.0 and provides publishing, subscribing, service
    calls, actionlib, TF, and other essential ROS functionality.
    Unlike the rospy library, this does not require a local ROS environment,
    allowing usage from platforms other than Linux.
  doc_url: https://roslibpy.readthedocs.io
  dev_url: https://github.com/gramaziokohler/roslibpy

extra:
  recipe-maintainers:
    - gonzalocasas
    - beverlylytle
