{% set name = "roslibpy" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: abc767e00f8e0a045b143fd829977ac4cd2a56175f2849a7dfd5140b3c6ce60b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - roslibpy=roslibpy.__main__:main

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - autobahn >=17.10
    - twisted >=17.9

test:
  imports:
    - roslibpy

about:
  home: https://github.com/gramaziokohler/roslibpy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python ROS Bridge library
  description: |
    Python ROS Bridge library allows to use Python and IronPython to interact
    with ROS, the open-source robotic middleware. It uses WebSockets to
    connect to rosbridge 2.0 and provides publishing, subscribing, service
    calls, actionlib, TF, and other essential ROS functionality.
    Unlike the rospy library, this does not require a local ROS environment,
    allowing usage from platforms other than Linux.
  doc_url: https://roslibpy.readthedocs.io
  dev_url: https://github.com/gramaziokohler/roslibpy

extra:
  recipe-maintainers:
    - gonzalocasas
    - beverlylytle
