appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: F71SChNqKTg9ICxzSpKBWo7OaUE6hIUAr8RYv8sMZdt/+WdVvmS/0UTPYrcGm8sZmxnvLGGwRCyISEl/HXP2HXQvsxIGEyPNUCTIOTk5RK9cBdGDJ/IeDJ3mQYBCwFnE8J6rTn1yKJgp/Cm8Mv03j2dYzjXA4Qhz5eBWgyfJypMBjIsSfaE4DhQwisZ1DNTCmv/+0fgnnLkzYTZCMsAnhowAOY78mdnGlaaL8UHkY0JNALFZTu291r7ilVitMrCeB9F2z6QbWtEnSamUve7pUne0T/TT5DfChCDXdASpfOq4V4awjrGbvMYkpFEu+qB5tu6XJL7hYaXKyBfYDix0VDcRk3n/iZpNzIHgdE69wghcTXkRCOhoYweISrQvhO3F/SB2JsB+zWpslH1VcjgIAFFyeYD5d3TJdsgBfQcpjKjZM3qIEPa3HV6hR5r+a2bYKmIgNZBKBA17n6Yvci+rSVWX4inkgQq4wljNwPeez9Vp7C2ClviiGPrKJrkX9eCwhXjOBLJlO7zNpl9GYRmDOE/Uuv0FS54A+5d3u/mrvCQj1iIISx77N3Xm+HVoqV9Tnd9DAYvMMnKnbEJ0fT6kUzIYZHA9hm+iw+6FsvMImZO0oyJUR1e6mJQ3Y5fdvQadG+K3QcXD86IrVBhOnMfRdkXypRZOSzOXJupRNW6q0h0=}
